steps:
  - id: 'Lint YAML'
    name: 'cytopia/yamllint'
    entrypoint: sh
    args:
      - -c
      - | # Recursively find yaml files (yamllint must be run in directory)
        find . -name "*.yaml" -not -path "./testing/*" -not -path "*.lint.cloudbuild.yaml" \
          -exec sh -c '
          root=$(pwd)
          lint () {
            cd "$root" || exit
            dir=$(dirname "$@")
            cd "$dir" || exit
            file=$(basename "$@")
            yamllint -d relaxed -f parsable "$file" | tee /proc/1/fd/1 | grep -q "error"
            if [[ $? -eq 0 ]] ; then error=1 ; fi
          }
          lint "$@"' sh {} \;
        if [[ $error -eq 1 ]] ; then exit 1 ; fi
  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform init"]
  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform plan"]
  - id: 'tf apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform apply -auto-approve"]
options:
  logging: CLOUD_LOGGING_ONLY
