timeout: 1200s
steps:
# terraform init -input=false
- name: hashicorp/google
  args:
  - init
  - -input=false
# terraform validate
- name: hashicorp/google
  args:
  - validate
# terraform plan -input=false -out=tfplan
- name: hashicorp/google
  args:
  - plan
  - -input=false
  - -out=tfplan
# terraform apply -auto-approve -input=false tfplan
- name: hashicorp/google
  args:
  - apply
  - -auto-approve
  - -input=false
  - tfplan
artifacts:
  objects:
    location: 'gs://${_ARTIFACT_BUCKET_NAME}/terraform/cloudbuild/apply/$BUILD_ID'
    paths: ['cloudbuild-tf-apply.yaml', 'tfplan']
