steps:
  - id: 'Lint install'
    entrypoint: "bash"
    name: 'ghcr.io/antonbabenko/pre-commit-terraform:v1.77.0'
    args: ["-c","pre-commit install --config .pre-commit-config.yaml"]
  - id: 'Lint check'
    waitFor: ['Lint install']
    entrypoint: "bash"
    args: ["-c","pre-commit run -a"]
  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform init"]
  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform plan"]
#  - id: 'tf apply'
#    name: 'hashicorp/terraform:1.0.0'
#    entrypoint: sh
#    args: ["-c","terraform apply -auto-approve"]
options:
  logging: CLOUD_LOGGING_ONLY
